### ISSUE TITLE
[torchx/ray] Properly implement torchx.scheduler API in the prototype Ray support

### ISSUE THREAD

**Issue by kiukchung** [pytorch/torchx#449]
## 🐛 Bug

The prototype ray scheduler support in TorchX needs adjustments to make it fully torchx.scheduler.Scheduler API compatible

Module (check all that applies):
 * [ ] `torchx.spec`
 * [ ] `torchx.component`
 * [ ] `torchx.apps`
 * [ ] `torchx.runtime`
 * [ ] `torchx.cli`
 * [x] `torchx.schedulers`
 * [ ] `torchx.pipelines`
 * [ ] `torchx.aws`
 * [ ] `torchx.examples`
 * [ ] `other`

## To Reproduce
See: https://github.com/pytorch/torchx/runs/5842634727?check_suite_focus=true

## List of TODOs

* `describe()`: Properly fill out `hostname` in replica status (currently sets it as as an empty string `""` (see: [link](https://github.com/pytorch/torchx/blob/main/torchx/schedulers/ray_scheduler.py#L330))). Results in the AppStatus being printed out as:
```
Final status: AppStatus:
  msg: <NONE>
  num_restarts: -1
  roles:
  - replicas:
    - hostname: ''
      id: 0
      role: ray
      state: !!python/object/apply:torchx.specs.api.AppState
      - 5
      structured_error_msg: <NONE>
    role: ray
  state: FAILED (5)
  structured_error_msg: <NONE>
  ui_url: null
```

* `log_iter()`: Either log/throw an exception when unsupported fields (regex, should_tail, stream, role_name) are set rather than silently swallowing the set values and defaulting to the most basic behavior. Results in a confusing behavior where the entire application's logs are returned when calling `log_iter(role_name="foo")`

* AppHandle (current example: `ray://test-runner/127.0.0.1:8265-raysubmit_vv7QafEHEHKFcYjA`): 
    * Do not encode ray head node's URL in the AppHandle. Rather use the `runoption` to accept the head node URL
    * Add the jobname in the app handle. Currently the job name is not present in the apphandle making it hard to visually inspect the app handle.

* <TODO> there may be more just listed out what I know so far.
*   
## Environment

 - torchx version (e.g. 0.1.0rc1): torchx-0.1.2
 - Python version: 3.8
 - OS (e.g., Linux): Linux
 - How you installed torchx (`conda`, `pip`, source, `docker`): pip
