### ISSUE TITLE
Volcano job scheduling issues due to bad upgrades

### ISSUE THREAD

**Issue by d4l3k** [pytorch/torchx#464]
This is an after the fact issue to help anyone who stumbles upon it later resolve the issue.

## Pod won't schedule due to CreateContainerConfigError

```
Warning  Failed     12m (x12 over 15m)    kubelet  Error: couldn't find key VC_PYTHON-0_HOSTS in ConfigMap default/torchxcomponentspython-bwg4m0sktd9mwc-svc
```

```
    state:
      waiting:
        message: couldn't find key VC_PYTHON-0_HOSTS in ConfigMap default/torchxcomponentspython-bwg4m0sktd9mwc-svc
        reason: CreateContainerConfigError
```

This is likely due to a Volcano version upgrade issue. Volcano 1.4 changed the ENV key format to correctly handle `-` characters. This means if a job was submitted under Volcano 1.3 and then is upgraded to Volcano 1.4 before running the job will fail to schedule. You just need to relaunch your job under the new version.

## Partial Upgrade Issues

```
Error creating pods: [failed to create pod pv5xp2lpf65vz-python-0-0, err: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"Internal error occurred: failed calling webhook \"mutatepod.volcano.sh\": the server could not find the requested resource", Reason:"InternalError", Details:(*v1.StatusDetails)(0xc002a125a0), Code:500}}]
```

When you upgrade Volcano you need to completely delete the `volcano-system` namespace and all resources within it before running `kubectl apply .../development.yaml`. If you don't, some of the setup jobs resources will conflict and won't run for the new version leaving the cluster in a bad state.
