### ISSUE TITLE
KFP adaptor seems to make invalid KFP app package(.yaml)

### ISSUE THREAD

**Issue by helloybz** [pytorch/torchx#647]
## 🐛 Bug

I've just copied the code snippets in this [tutorial](https://pytorch.org/torchx/latest/examples_pipelines/kfp/intro_pipeline.html), **INTRO KUBEFLOW PIPELINES EXAMPLE**, but the produced pipeline.yaml file doesn't seem to following Argo Worlfkow Templates well.

Module (check all that applies):
 * [X] `torchx.spec`
 * [ ] `torchx.component`
 * [ ] `torchx.apps`
 * [ ] `torchx.runtime`
 * [ ] `torchx.cli`
 * [ ] `torchx.schedulers`
 * [X] `torchx.pipelines`
 * [ ] `torchx.aws`
 * [ ] `torchx.examples`
 * [ ] `other`

## To Reproduce

1. Activate an appropriate venv with torch=0.3.0 and kfp==1.6.2
1. Copy all the code snippets in the tutorial above and paste into a new file `pipeline.py`.
1. Run `python pipeline.py`
1. Check the `spec` section in the produced `pipeline.yaml` file.

## Expected behavior

- `spec.entrypoint` is supposed to be `examples-intro-worker`, but it becomes `pipeline`
```yaml
spec:
  entrypoint: pipeline
  templates:
  - name: examples-intro-worker
    container:
      args: []
```
```yaml
spec:
  entrypoint: examples-intro-worker
  templates:
  - name: examples-intro-worker
    container:
      args: []
```
## Environment

```
Versions of CLIs:
AWS CLI: aws-cli/2.8.3 Python/3.10.8 Darwin/21.6.0 source/arm64 prompt/off
gCloud CLI: None
AZ CLI: None
Slurm: N/A
Docker: 20.10.20, build 9fdeb9c
kubectl: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/arm64"}

torchx dev package versions:
aiobotocore:2.4.0
flake8:5.0.4
kfp:1.8.14
kfp-pipeline-spec:0.1.16
kfp-server-api:1.8.5
pyre-extensions:0.0.30
pytorch-lightning:1.8.0
requests:2.28.1
requests-oauthlib:1.3.1
requests-toolbelt:0.10.1
strip-hints:0.1.10
torch:1.12.0
torchmetrics:0.10.2
torchx:0.3.0

torchx config:
N/A
```
 - torchx version (e.g. 0.1.0rc1): 0.3.0
 - Python version: 3.10.8
 - OS (e.g., Linux): macOS 12.5.1
 - How you installed torchx (`conda`, `pip`, source, `docker`): pip (poetry)
 - Docker image and tag (if using docker): x
 - Git commit (if installed from source): x
 - Execution environment (on-prem, AWS, GCP, Azure etc): on-prem (local)
 - Any other relevant information:
